apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gyalpo-deploy
  name: gyalpo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyalpo-deploy
  template:
    metadata:
      labels:
        app: gyalpo-deploy
    spec:
      containers:
      - image: gyalpo97/gyalpo:19
        name: gyalpo
